/* ============================================================================
 * qspi_flash.c -- wrapper over Infineon's serial-flash (cy_serial_flash_qspi)
 * ============================================================================ */

#include "qspi_flash.h"
#include "cy_serial_flash_qspi.h"
#include "cycfg_qspi_memslot.h"     /* smifBlockConfig — describes the chip */
#include "cybsp.h"

/* SMIF runs from a clock; 50 MHz is conservative-safe for this flash. The
 * serial-flash lib divides the source clock down to hit this. */
#define QSPI_BUS_FREQ_HZ    (50000000UL)

static bool s_inited = false;

cy_rslt_t qspi_flash_init(void)
{
    if (s_inited) return CY_RSLT_SUCCESS;

    /* cy_serial_flash_qspi_init takes the memory-slot config (generated by
     * the Device Configurator -- it's the chip's "datasheet in struct form"),
     * the 6 QSPI pins, and the bus clock. The lib sets up SMIF and probes
     * the flash. */
    cy_rslt_t rslt = cy_serial_flash_qspi_init(
            smifMemConfigs[0],            /* first (only) configured mem slot */
            CYBSP_QSPI_D0, CYBSP_QSPI_D1, CYBSP_QSPI_D2, CYBSP_QSPI_D3,
            NC, NC, NC, NC,               /* no second octal nibble on this part */
            CYBSP_QSPI_SCK, CYBSP_QSPI_SS,
            QSPI_BUS_FREQ_HZ);
    if (rslt != CY_RSLT_SUCCESS) return rslt;

    s_inited = true;
    return CY_RSLT_SUCCESS;
}

cy_rslt_t qspi_flash_read(uint32_t addr, void *buf, size_t len)
{
    if (!s_inited) return CY_RSLT_TYPE_ERROR;
    return cy_serial_flash_qspi_read(addr, len, (uint8_t *)buf);
}

cy_rslt_t qspi_flash_erase(uint32_t addr, size_t len)
{
    if (!s_inited) return CY_RSLT_TYPE_ERROR;
    return cy_serial_flash_qspi_erase(addr, len);
}

cy_rslt_t qspi_flash_write(uint32_t addr, const void *buf, size_t len)
{
    if (!s_inited) return CY_RSLT_TYPE_ERROR;
    return cy_serial_flash_qspi_write(addr, len, (const uint8_t *)buf);
}

size_t qspi_flash_total_size(void)
{
    return s_inited ? cy_serial_flash_qspi_get_size() : 0;
}

size_t qspi_flash_sector_size(void)
{
    /* erase-sector size for a given address (uniform on this part) */
    return s_inited ? cy_serial_flash_qspi_get_erase_size(0) : 0;
}